name: iControlU
version: 1.5.8
main: me.firebreath15.icontrolu.iControlU
commands:
  icu:
    description: Main command for iControlU
    usage: /icu
    permission: icu.use
    permission-message: You don't have permission
permissions:
  icu.use:
    default: true
  icu.control:
    default: op
  icu.stop:
    default: op
  icu.exempt:
    default: false